// Generates middleware/node-red/flows.json from the readable sources in
// middleware/node-red/src. Run: node scripts/build-flows.js
// Use --check to fail if flows.json is out of date (used by tests).
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const src = (name) => fs.readFileSync(path.join(root, 'middleware/node-red/src', name), 'utf8').replace(/\r\n/g, '\n');
const TAB = 'iot55-flow';
const BROKER = 'iot55-broker';

const mqttIn = (id, topic, y) => ({
  id, type: 'mqtt in', z: TAB, name: topic.replace('iot55/device01/', ''), topic, qos: '1',
  datatype: 'utf8', broker: BROKER, nl: false, rap: true, rh: 0, inputs: 0, x: 150, y, wires: [['state-engine']]
});
const fn = (id, name, file, outputs, x, y, wires, outputLabels) => ({
  id, type: 'function', z: TAB, name, func: src(file), outputs, timeout: 0, noerr: 0,
  initialize: '', finalize: '', libs: [], x, y, wires, ...(outputLabels ? { outputLabels } : {})
});

const flows = [
  { id: TAB, type: 'tab', label: 'IoT 55 - Energy Automation', disabled: false,
    info: 'Generated by scripts/build-flows.js from middleware/node-red/src. Edit the sources, not this file.' },
  { id: BROKER, type: 'mqtt-broker', name: 'IoT55 broker', broker: '${MQTT_HOST}', port: '${MQTT_PORT}',
    clientid: '', autoConnect: true, usetls: false, protocolVersion: '4', keepalive: '30', cleansession: true,
    autoUnsubscribe: true, birthTopic: '', closeTopic: '', willTopic: '' },

  { id: 'comment-uplink', type: 'comment', z: TAB, name: 'UPLINK: ESP32 -> MQTT -> state engine', x: 190, y: 40, wires: [] },
  mqttIn('in-telemetry', 'iot55/device01/telemetry', 80),
  mqttIn('in-status', 'iot55/device01/status', 120),
  mqttIn('in-event', 'iot55/device01/event', 160),
  mqttIn('in-relay-state', 'iot55/device01/relay/state', 200),
  { id: 'scheduler-tick', type: 'inject', z: TAB, name: 'Tick 5s (scheduler + heartbeat)', props: [{ p: 'topic', vt: 'str' }],
    repeat: '5', crontab: '', once: true, onceDelay: '1', topic: 'internal/tick', x: 190, y: 260, wires: [['state-engine']] },

  fn('state-engine', 'State engine: validate, FSM, rules, log', 'state-engine.js', 4, 560, 180,
    [['out-downlink'], ['out-event', 'debug-events'], ['out-state'], ['http-response']],
    ['MQTT downlink', 'Event log', 'System state', 'HTTP reply']),

  { id: 'comment-downlink', type: 'comment', z: TAB, name: 'DOWNLINK: commands -> MQTT -> ESP32', x: 900, y: 40, wires: [] },
  { id: 'out-downlink', type: 'mqtt out', z: TAB, name: 'cmd/* (downlink)', topic: '', qos: '', retain: '', broker: BROKER, x: 900, y: 120, wires: [] },
  { id: 'out-event', type: 'mqtt out', z: TAB, name: 'event (log)', topic: '', qos: '1', retain: 'false', broker: BROKER, x: 890, y: 170, wires: [] },
  { id: 'debug-events', type: 'debug', z: TAB, name: 'Event log', active: true, tosidebar: true, console: false,
    complete: 'payload', targetType: 'msg', statusVal: '', statusType: 'auto', x: 890, y: 210, wires: [] },
  { id: 'out-state', type: 'mqtt out', z: TAB, name: 'system/state (retained)', topic: '', qos: '1', retain: '', broker: BROKER, x: 920, y: 250, wires: [] },

  { id: 'comment-api', type: 'comment', z: TAB, name: 'APPLICATION API (dashboard via nginx /api)', x: 220, y: 340, wires: [] },
  { id: 'api-state-in', type: 'http in', z: TAB, name: 'GET /api/state', url: '/api/state', method: 'get', upload: false, x: 160, y: 380, wires: [['api-state']] },
  fn('api-state', 'Read state', 'api-state.js', 1, 380, 380, [['http-response']]),
  { id: 'api-command-in', type: 'http in', z: TAB, name: 'POST /api/command', url: '/api/command', method: 'post', upload: false, x: 170, y: 420, wires: [['api-command']] },
  fn('api-command', 'To state engine', 'api-command.js', 1, 380, 420, [['state-engine']]),
  { id: 'http-response', type: 'http response', z: TAB, name: 'HTTP response', statusCode: '', headers: {}, x: 900, y: 380, wires: [] },

  { id: 'catch-errors', type: 'catch', z: TAB, name: 'Catch errors', scope: null, uncaught: false, x: 150, y: 480, wires: [['debug-errors']] },
  { id: 'debug-errors', type: 'debug', z: TAB, name: 'Errors', active: true, tosidebar: true, console: true,
    complete: 'error', targetType: 'msg', statusVal: '', statusType: 'auto', x: 380, y: 480, wires: [] }
];

const target = path.join(root, 'middleware/node-red/flows.json');
const json = JSON.stringify(flows, null, 4) + '\n';
if (process.argv.includes('--check')) {
  const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8').replace(/\r\n/g, '\n') : '';
  if (current !== json) {
    console.error('flows.json is out of date: run node scripts/build-flows.js');
    process.exit(1);
  }
  console.log('flows.json is up to date');
} else {
  fs.writeFileSync(target, json);
  console.log(`Wrote ${flows.length} nodes to ${path.relative(root, target)}`);
}
